server:
  port: 80
spring:
  application:
    name: cloud-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: zhangyukang
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/db_02?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    druid:
      initial-size: 10
      max-active: 10
  #配置consul客户端
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
#mybatis的配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # 指定mapper映射的路径
  type-aliases-package: com.coderman.payment.model
  configuration:
    map-underscore-to-camel-case: true
#logback配置
logging:
  pattern:
    console: '%d -%msg%n'
  level:
    com:
      coderman: debug
