server:
  port: 8002
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: zhangyukang
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/db_01?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    druid:
      initial-size: 10
      max-active: 10
#eureka客户端的配置
eureka:
  instance:
    instance-id: cloud-payment-service-8002 # 修改实例的别名
    prefer-ip-address: true # 显示IP
  client:
    service-url:
      defaultZone: http://server1.com:7001/eureka/,http://server2.com:7002/eureka/,http://server3.com:7003/eureka/ #注册服务到eureka服务器
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # 指定mapper映射的路径
  type-aliases-package: com.coderman.payment.model
  configuration:
    map-underscore-to-camel-case: true
#logback配置
logging:
  pattern:
    console: '%d -%msg%n'
  level:
    com:
      coderman: debug
