server:
  port: 7001
eureka:
  instance:
    hostname: server1.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://server2.com:7002/eureka/,http://server3.com:7003/eureka/
